### ISSUE TITLE
support AWS_SESSION_TOKEN

### ISSUE THREAD

**Issue by xZanon** [d3QUone/aiosqs#12]
Hi, 

are you planning to implement option to authenticate with 
AWS_ACCESS_KEY_ID="*" ,  AWS_SECRET_ACCESS_KEY="*", and AWS_SESSION_TOKEN="*"

Regards,

**Comment by d3QUone** [comment]
Hi @xZanon, check out the release: https://github.com/d3QUone/aiosqs/releases/tag/v1.0.6

We've added support for `aws_session_token`
