### ISSUE TITLE
unhandled NameSpace in AWS response 

### ISSUE THREAD

**Issue by xZanon** [d3QUone/aiosqs#14]
Problem with parsing xml respond from AWS that contains namespace.

Current response from AWS looks like : 
`<GetQueueUrlResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">`
`    <GetQueueUrlResult>`
`        <QueueUrl>`
`        https://sqs.....</QueueUrl>`
`    </GetQueueUrlResult>`

and the parser does not xpath it correctly. 

Quick and dirty solution - remove 'xmlns' from response body in file : parser.py, function : `parse_xml_result_response()`
something like  `body = re.sub(r' xmlns=".*"','', body)`

The other way is to handle NameSpaces by  lxml  or start using different library  

Regards ,

**Comment by d3QUone** [comment]
Hi @xZanon, thank you for your report! Confirming, there is a bug, I'll work on a proper fix soon.
